# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Fangtian Zhong
jobtitle: "Assitant Professor"
email: fangtian.zhong@montana.edu
description: > # this means to ignore newlines until "baseurl:"
  Dr. Fangtian's personal academic website.
  Updated biography on About page & publications on Research page & courses on Teaching page

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://https://fangtian-zhong.github.io"
workurl: "http://www.cs.montana.edu/directory/2458165/fangtian-zhong"
googlescholar_username: byrWN40AAAAJ&hl=zh-CN
researchgate_username:  Fangtian-Zhong
pubmed_name:        Fangtian+Zhong
dblp_id:            276/3588
github_username:    fangtian-zhong
twitter_username:   Fangtian_Zhong
linkedin_username:  zjf5176

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# URL settings
permalink: blogs/:categories/:title
collections:
  lectures:
    output: true
    permalink: /lectures/:categories/:path

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
